import { Car } from '@monoscript/shared';
import { Person } from '@monoscript/shared';

export const cars: Car[] = [
  {
    id: '1',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    color: 'Silver',
    price: 25000,
    mileage: 15000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    vin: '1HGBH41JXMN109186',
    isAvailable: true,
  },
  {
    id: '2',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    color: 'Red',
    price: 45000,
    mileage: 5000,
    fuelType: 'electric',
    transmission: 'automatic',
    vin: '5YJ3E1EA1JF000317',
    isAvailable: true,
  },
  {
    id: '3',
    make: 'Ford',
    model: 'F-150',
    year: 2021,
    color: 'Blue',
    price: 35000,
    mileage: 25000,
    fuelType: 'gasoline',
    transmission: 'automatic',
    vin: '1FTFW1ET5DFC10312',
    isAvailable: false,
  },
  {
    id: '4',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    color: 'White',
    price: 22000,
    mileage: 18000,
    fuelType: 'gasoline',
    transmission: 'manual',
    vin: '2HGFC2F59MH567890',
    isAvailable: true,
  },
  {
    id: '5',
    make: 'BMW',
    model: 'X5',
    year: 2023,
    color: 'Black',
    price: 60000,
    mileage: 10000,
    fuelType: 'hybrid',
    transmission: 'automatic',
    vin: 'WBAJB9C51KB123456',
    isAvailable: true,
  },
];
